<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1661078503967' stop='1661078512401'>
    <name>Edit Profile</name>
    <title>Edit Profile</title>
    <test-cases>
        <test-case start='1661078511189' status='broken' stop='1661078512309'>
            <name>edit profile</name>
            <title>edit profile</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>`cy.request()` failed on:
                
                https://api.unsplash.com/me
                
                The response we received from your web server was:
                
                  > 422: Unprocessable Entity
                
                This was considered a failure because the status code was not `2xx` or `3xx`.
                
                If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`
                
                -----------------------------------------------------------
                
                The request we sent was:
                
                Method: PUT
                URL: https://api.unsplash.com/me
                Headers: {
                  "Connection": "keep-alive",
                  "Authorization": "Bearer INux6IxQuZLjnBq9Sg00riAK7CNUNODvts_uA6EpGkY",
                  "accept": "application/json",
                  "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/10.6.0 Chrome/102.0.5005.148 Electron/19.0.8 Safari/537.36",
                  "cookie": "_gat=1; _sp_ses.0295=*; _gid=GA1.2.450129159.1661078506; ugid=362e4df03dfadb940f70063d8ad70d185536928; _ga=GA1.2.1537267963.1661078506; _sp_id.0295=9a7bd37c3f6d30ef.1661078507.1.1661078511.1661078507.4daa5805-41b4-4817-975b-dc5ada5589ab",
                  "accept-encoding": "gzip, deflate",
                  "content-type": "application/json",
                  "content-length": 214
                }
                Body: {"username":"default_username","first_name":"default firstname","last_name":"default lastname","url":"https://default.com","location":"default location","bio":"default bio","instagram_username":"default_instagram"}
                
                -----------------------------------------------------------
                
                The response we got was:
                
                Status: 422 - Unprocessable Entity
                Headers: {
                  "connection": "keep-alive",
                  "server": "Cowboy",
                  "content-type": "application/json",
                  "access-control-allow-origin": "*",
                  "access-control-request-method": "*",
                  "access-control-allow-headers": "*",
                  "access-control-expose-headers": "Link,X-Total,X-Per-Page,X-RateLimit-Limit,X-RateLimit-Remaining",
                  "cache-control": "private,max-age=0,stale-if-error=300,stale-while-revalidate=0",
                  "x-unsplash-version": "v1",
                  "content-language": "en",
                  "x-ratelimit-limit": "50",
                  "x-ratelimit-remaining": "31",
                  "x-request-id": "f8a773ad-d10c-4179-b8f9-06d9c1c83bb2",
                  "x-runtime": "0.271341",
                  "content-encoding": "gzip",
                  "strict-transport-security": "max-age=31536000; includeSubDomains",
                  "via": "1.1 vegur, 1.1 varnish, 1.1 varnish",
                  "accept-ranges": "bytes",
                  "date": "Sun, 21 Aug 2022 10:41:51 GMT",
                  "x-served-by": "cache-iad-kjyo7100091-IAD, cache-qpg1259-QPG",
                  "x-cache": "MISS, MISS",
                  "x-cache-hits": "0, 0",
                  "x-timer": "S1661078511.781697,VS0,VE505",
                  "vary": "Accept-Encoding, Origin,Authorization,Accept-Language,Accept",
                  "transfer-encoding": "chunked"
                }
                Body: {
                  "errors": [
                    "Username has already been taken"
                  ]
                }
                
                
                https://on.cypress.io/request
                
                Because this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `Edit Profile`</message>
                <stack-trace>CypressError: `cy.request()` failed on:
                
                https://api.unsplash.com/me
                
                The response we received from your web server was:
                
                  > 422: Unprocessable Entity
                
                This was considered a failure because the status code was not `2xx` or `3xx`.
                
                If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`
                
                -----------------------------------------------------------
                
                The request we sent was:
                
                Method: PUT
                URL: https://api.unsplash.com/me
                Headers: {
                  "Connection": "keep-alive",
                  "Authorization": "Bearer INux6IxQuZLjnBq9Sg00riAK7CNUNODvts_uA6EpGkY",
                  "accept": "application/json",
                  "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/10.6.0 Chrome/102.0.5005.148 Electron/19.0.8 Safari/537.36",
                  "cookie": "_gat=1; _sp_ses.0295=*; _gid=GA1.2.450129159.1661078506; ugid=362e4df03dfadb940f70063d8ad70d185536928; _ga=GA1.2.1537267963.1661078506; _sp_id.0295=9a7bd37c3f6d30ef.1661078507.1.1661078511.1661078507.4daa5805-41b4-4817-975b-dc5ada5589ab",
                  "accept-encoding": "gzip, deflate",
                  "content-type": "application/json",
                  "content-length": 214
                }
                Body: {"username":"default_username","first_name":"default firstname","last_name":"default lastname","url":"https://default.com","location":"default location","bio":"default bio","instagram_username":"default_instagram"}
                
                -----------------------------------------------------------
                
                The response we got was:
                
                Status: 422 - Unprocessable Entity
                Headers: {
                  "connection": "keep-alive",
                  "server": "Cowboy",
                  "content-type": "application/json",
                  "access-control-allow-origin": "*",
                  "access-control-request-method": "*",
                  "access-control-allow-headers": "*",
                  "access-control-expose-headers": "Link,X-Total,X-Per-Page,X-RateLimit-Limit,X-RateLimit-Remaining",
                  "cache-control": "private,max-age=0,stale-if-error=300,stale-while-revalidate=0",
                  "x-unsplash-version": "v1",
                  "content-language": "en",
                  "x-ratelimit-limit": "50",
                  "x-ratelimit-remaining": "31",
                  "x-request-id": "f8a773ad-d10c-4179-b8f9-06d9c1c83bb2",
                  "x-runtime": "0.271341",
                  "content-encoding": "gzip",
                  "strict-transport-security": "max-age=31536000; includeSubDomains",
                  "via": "1.1 vegur, 1.1 varnish, 1.1 varnish",
                  "accept-ranges": "bytes",
                  "date": "Sun, 21 Aug 2022 10:41:51 GMT",
                  "x-served-by": "cache-iad-kjyo7100091-IAD, cache-qpg1259-QPG",
                  "x-cache": "MISS, MISS",
                  "x-cache-hits": "0, 0",
                  "x-timer": "S1661078511.781697,VS0,VE505",
                  "vary": "Accept-Encoding, Origin,Authorization,Accept-Language,Accept",
                  "transfer-encoding": "chunked"
                }
                Body: {
                  "errors": [
                    "Username has already been taken"
                  ]
                }
                
                
                https://on.cypress.io/request
                
                Because this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `Edit Profile`
                    at https://unsplash.com/__cypress/runner/cypress_runner.js:154196:80
                    at tryCatcher (https://unsplash.com/__cypress/runner/cypress_runner.js:11318:23)
                    at Promise._settlePromiseFromHandler (https://unsplash.com/__cypress/runner/cypress_runner.js:9253:31)
                    at Promise._settlePromise (https://unsplash.com/__cypress/runner/cypress_runner.js:9310:18)
                    at Promise._settlePromise0 (https://unsplash.com/__cypress/runner/cypress_runner.js:9355:10)
                    at Promise._settlePromises (https://unsplash.com/__cypress/runner/cypress_runner.js:9435:18)
                    at _drainQueueStep (https://unsplash.com/__cypress/runner/cypress_runner.js:6025:12)
                    at _drainQueue (https://unsplash.com/__cypress/runner/cypress_runner.js:6018:9)
                    at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://unsplash.com/__cypress/runner/cypress_runner.js:6034:5)
                    at Async.drainQueues (https://unsplash.com/__cypress/runner/cypress_runner.js:5904:14)
                From Your Spec Code:
                    at Context.eval (https://unsplash.com/__cypress/tests?p=cypress\support\e2e.js:175:6)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>